# @package _group_
batch_size: 2400
num_classes: 10
seed: 1234
plot: True
show_plot: True
save_dir: ./repr_analysis_results
ide:
  calculate: True
  nres: 5
  fraction: 0.5
  plot_together: True
rmds:
  calculate: True
cka:
  calculate: True
