# @package _group_
name: vgg6a
dropout: 0
num_layers: 1
num_hidden: 1024
loss:
  no_batch_norm: False
  backprop: False
  loss_sup: predsim
  bio: False
  no_detach: False
  dim_in_decoder: 4096
  alpha: 0
  beta: 0.99
  print_stats: False