# @package _group_
gpus: 0
lr: 0.001
lr_scheduler: True
lr_gamma: 0.9
epochs: 2
batch_size: 16
optim: adam
weight_decay: 0
progress_bar: True
data_loader_workers: 3
checkpointing: True
checkpoint_dir: checkpoints
seed: 1234
sam:
  active: False
  rho: 0.5
  adaptive: True
