# default training configuration
defaults:
    - train: train.yaml
    - model: vgg.yaml
    - dataset: cifar10.yaml
    #- log: null  # set logger here or use command line (e.g. `python run.py logger=wandb`)

    #- experiment: null

    - hydra: default.yaml

logging_level: debug

work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/../data/


