# @package _group_
gpus: 1
lr: 0.0005
epochs: 2
batch_size: 128
optim: adam
weight_decay: 0
progress_bar: True
data_loader_workers: 3
checkpointing: True
checkpoint_dir: checkpoints
seed: 1234
sam: True
